version: '3'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: digitalocean.com/php
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - app-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    #Mongo Service
    db:
        image: mongo
        container_name: db
        restart: unless-stopped
        ports:
            - "27020:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ""
            MONGO_INITDB_ROOT_PASSWORD: ""
        command: --storageEngine wiredTiger

#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local